project:
  type: website
  output-dir: docs

website:
  title: "TRAN Thu Le's Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - topics.qmd
      - research.qmd
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



